// Generated by gencpp from file tkdnn_ros/bboxes.msg
// DO NOT EDIT!


#ifndef TKDNN_ROS_MESSAGE_BBOXES_H
#define TKDNN_ROS_MESSAGE_BBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tkdnn_ros/bbox.h>

namespace tkdnn_ros
{
template <class ContainerAllocator>
struct bboxes_
{
  typedef bboxes_<ContainerAllocator> Type;

  bboxes_()
    : header()
    , bboxes()  {
    }
  bboxes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tkdnn_ros::bbox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tkdnn_ros::bbox_<ContainerAllocator> >::other >  _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::tkdnn_ros::bboxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tkdnn_ros::bboxes_<ContainerAllocator> const> ConstPtr;

}; // struct bboxes_

typedef ::tkdnn_ros::bboxes_<std::allocator<void> > bboxes;

typedef boost::shared_ptr< ::tkdnn_ros::bboxes > bboxesPtr;
typedef boost::shared_ptr< ::tkdnn_ros::bboxes const> bboxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tkdnn_ros::bboxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tkdnn_ros::bboxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tkdnn_ros::bboxes_<ContainerAllocator1> & lhs, const ::tkdnn_ros::bboxes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bboxes == rhs.bboxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tkdnn_ros::bboxes_<ContainerAllocator1> & lhs, const ::tkdnn_ros::bboxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tkdnn_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tkdnn_ros::bboxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tkdnn_ros::bboxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkdnn_ros::bboxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tkdnn_ros::bboxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkdnn_ros::bboxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tkdnn_ros::bboxes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tkdnn_ros::bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce0fdf9895bce90aca959558c92d32d";
  }

  static const char* value(const ::tkdnn_ros::bboxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce0fdf9895bce90ULL;
  static const uint64_t static_value2 = 0xaca959558c92d32dULL;
};

template<class ContainerAllocator>
struct DataType< ::tkdnn_ros::bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tkdnn_ros/bboxes";
  }

  static const char* value(const ::tkdnn_ros::bboxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tkdnn_ros::bboxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bbox[] bboxes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tkdnn_ros/bbox\n"
"float64 score\n"
"int64 x\n"
"int64 y\n"
"int64 width\n"
"int64 height\n"
"int16 id\n"
"string Class\n"
;
  }

  static const char* value(const ::tkdnn_ros::bboxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tkdnn_ros::bboxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bboxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tkdnn_ros::bboxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tkdnn_ros::bboxes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tkdnn_ros::bbox_<ContainerAllocator> >::stream(s, indent + "    ", v.bboxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKDNN_ROS_MESSAGE_BBOXES_H
